name: Issue Report
description: 이슈를 상세하게 알려주시면 답변 받을 확률이 Up!
title: "[Question]: "
labels: "question"
assignees:
  - youngjinmo
body:
  - type: markdown
    attributes:
      value: |
        본 템플릿을 통해 이슈를 작성해주세요 :)
  - type: dropdown
    id: book
    attributes:
      label: Book
      description: 어떤 책을 읽고 계신가요?
      options:
        - 토비의 스프링 (Vol.1)
        - 토비의 스프링 (Vol.2)
    validations:
      required: true
  - type: input
    id: page
    attributes:
      label: Page
      description: 몇 페이지를 읽다가 발생한 이슈인가요?
      placeholder: ex. p.470 ~ p.472
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: My Issue
      description: 구체적으로 어떤 이슈인지 알려주세요
      placeholder: ex. 메소드 레벨에서 핸들러 매핑 내부 동작원리가 궁금해요.
    validations:
      required: true

